### ISSUE TITLE
influxdb reports invalid number

### ISSUE THREAD

**Issue by brianmay** [influxdb-rs/influxdb-rust#121]
After upgrading to 0.6.0 I keep getting the following error:

```
2023-05-19T03:56:51.245268Z ERROR brian_backend::amber: Failed to write to influxdb: InfluxDB encountered the following error: influxdb error: "{"error":"unable to parse 'amber/usage/E2 duration=30u,per_kwh=33.036441802978516,renewables=9.333999633789063,kwh=0,cost=0 1684411201000000000': invalid number"}
"
```

But If I downgrade to 0.5.2 it works fine. The schema in question is:

```
**#[derive(InfluxDbWriteable)]
struct UsageReading {
    duration: u16,
    per_kwh: f32,
    renewables: f32,
    kwh: f32,
    cost: f32,
    time: chrono::DateTime<Utc>,
}
```

This is with influxdb 1.10.0

**Comment by brianmay** [comment]
Still trying to understand how influxdb works, but seriously wondering if this has something to do with #113 and my duration field.

**Comment by brianmay** [comment]
Actually, I might be getting confused. My research shows that the 'u' postfix for unsigned integers is only supported for influxdb 2.x (reference:https://github.com/influxdata/influxdb/issues/17781), but I thought this library (based on other reports) only supported influxdb 1.x.

**Comment by msrd0** [comment]
Hi, thanks for your bug report.

> My research shows that the 'u' postfix for unsigned integers is only supported for influxdb 2.x (reference:influxdata/influxdb#17781)

That's interesting, the documentation for influxdb 1.8 seems to suggest the same: https://docs.influxdata.com/influxdb/v1.8/write_protocols/line_protocol_reference/#data-types. I wonder why this didn't cause any problems yet. @Empty2k12 has way more experience with influxdb, maybe he can comment.

> but I thought this library (based on other reports) only supported influxdb 1.x

As far as I know, this library supports the [backward-compatibility API of v2](https://test2.docs.influxdata.com/influxdb/v2.7/reference/api/influxdb-1x/) since #118. I never actually used it though.

**Comment by msrd0** [comment]
CC @mcronce

**Comment by Empty2k12** [comment]
Hey @brianmay @eflukx I have pushed #123 which makes the `u` suffix opt-in. It will be merged to main momentarily once @msrd0 is done reviewing. Could you test if this fixes the issue? Then we would be releasing the change

**Comment by brianmay** [comment]
So far not getting any errors, so fingers crossed that means it is working. 

Should now for sure tomorrow.
